import { PDFDocument, StandardFonts, rgb, type PDFFont } from "pdf-lib";
import { prisma } from "@/lib/prisma";
import { getDrive, ensureAssignmentTree, uploadOrReplace, downloadFile } from "@/lib/drive";

export type MergeOptions = {
  coverPage: boolean;
  separators: boolean;
  pageNumbers: boolean;
  tableOfContents: boolean;
};

/**
 * Storage seam: production uses Google Drive, tests use an in-memory map.
 * Keeping this injectable lets the merge logic be exercised without network.
 */
export type MergeStorage = {
  fetchPdf: (driveFileId: string) => Promise<Buffer>;
  saveFinal: (name: string, bytes: Buffer) => Promise<{ id: string; webViewLink: string | null }>;
};

export type PageMapEntry = {
  enrollmentNo: string;
  name: string;
  startPage: number;
  endPage: number;
};

const A4: [number, number] = [595.28, 841.89];
const INK = rgb(0.09, 0.09, 0.11);
const MUTED = rgb(0.42, 0.45, 0.5);
const ACCENT = rgb(0.31, 0.27, 0.9);

async function driveStorage(course: string, title: string): Promise<MergeStorage> {
  const drive = await getDrive();
  const tree = await ensureAssignmentTree(drive, course, title);
  return {
    fetchPdf: (fileId) => downloadFile(drive, fileId),
    saveFinal: (name, bytes) =>
      uploadOrReplace(drive, {
        name,
        parentId: tree.final,
        mimeType: "application/pdf",
        body: bytes,
      }),
  };
}

async function setStep(jobId: string, step: string, progress: number) {
  await prisma.mergeJob.update({ where: { id: jobId }, data: { step, progress } });
}

function drawCentered(page: ReturnType<PDFDocument["addPage"]>, text: string, font: PDFFont, size: number, y: number, color = INK) {
  const width = font.widthOfTextAtSize(text, size);
  page.drawText(text, { x: (A4[0] - width) / 2, y, size, font, color });
}

/**
 * Runs the whole merge for one job. Any single bad file fails the entire job
 * with the offending enrollment number named, rather than silently producing
 * a partial document.
 */
export async function runMergeJob(jobId: string, storage?: MergeStorage): Promise<void> {
  const job = await prisma.mergeJob.findUnique({
    where: { id: jobId },
    include: { assignment: true },
  });
  if (!job) throw new Error(`Merge job ${jobId} not found`);

  const options = ((job.pageMap as { options?: MergeOptions } | null)?.options ?? {
    coverPage: true,
    separators: true,
    pageNumbers: true,
    tableOfContents: true,
  }) as MergeOptions;

  try {
    await prisma.mergeJob.update({
      where: { id: jobId },
      data: { status: "RUNNING", step: "FETCHING", progress: 5 },
    });

    const submissions = await prisma.submission.findMany({
      where: { id: { in: job.includedSubmissions } },
      include: { student: true },
    });
    if (submissions.length === 0) throw new Error("No submissions were selected for this merge.");

    // Preserve the exact order the CR confirmed on the verification screen.
    const order = new Map(job.includedSubmissions.map((id, i) => [id, i]));
    submissions.sort((a, b) => (order.get(a.id) ?? 0) - (order.get(b.id) ?? 0));

    const store = storage ?? (await driveStorage(job.assignment.course, job.assignment.title));
    const out = await PDFDocument.create();
    const helv = await out.embedFont(StandardFonts.Helvetica);
    const helvBold = await out.embedFont(StandardFonts.HelveticaBold);

    if (options.coverPage) {
      const cover = out.addPage(A4);
      drawCentered(cover, job.assignment.course, helv, 12, 600, MUTED);
      drawCentered(cover, job.assignment.title, helvBold, 26, 560);
      cover.drawLine({
        start: { x: 160, y: 540 },
        end: { x: A4[0] - 160, y: 540 },
        thickness: 2,
        color: ACCENT,
      });
      drawCentered(cover, `Compiled submissions — ${submissions.length} students`, helv, 13, 505, MUTED);
      drawCentered(
        cover,
        new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" }),
        helv,
        11,
        482,
        MUTED
      );
      drawCentered(cover, "Generated by SubmitHub", helv, 9, 60, MUTED);
    }

    // The TOC is written after the merge (page numbers aren't known yet), so
    // reserve its pages now and keep references to fill in later.
    const tocPageCount = options.tableOfContents ? Math.max(1, Math.ceil(submissions.length / 30)) : 0;
    const tocPages = [];
    for (let i = 0; i < tocPageCount; i++) tocPages.push(out.addPage(A4));

    await setStep(jobId, "MERGING", 20);

    const pageMap: PageMapEntry[] = [];

    for (let i = 0; i < submissions.length; i++) {
      const sub = submissions[i];
      const label = `${sub.student.enrollmentNo} (${sub.student.name})`;

      if (!sub.pdfDriveFileId) {
        throw new Error(`${label} has no converted PDF. Exclude them or ask for a resubmission.`);
      }

      let bytes: Buffer;
      try {
        bytes = await store.fetchPdf(sub.pdfDriveFileId);
      } catch {
        throw new Error(`Could not download the file for ${label} from Google Drive.`);
      }

      if (options.separators) {
        const sep = out.addPage(A4);
        drawCentered(sep, sub.student.enrollmentNo, helvBold, 20, 470, ACCENT);
        drawCentered(sep, sub.student.name, helvBold, 16, 442);
        drawCentered(sep, sub.originalFilename, helv, 10, 418, MUTED);
      }

      const startPage = out.getPageCount() + 1;

      try {
        const src = await PDFDocument.load(bytes, { ignoreEncryption: true });
        if (src.isEncrypted) {
          throw new Error(`${label} submitted a password-protected PDF. Exclude them or ask for an unlocked copy.`);
        }
        const copied = await out.copyPages(src, src.getPageIndices());
        if (copied.length === 0) throw new Error(`${label} submitted a PDF with no pages.`);
        copied.forEach((p) => out.addPage(p));
      } catch (err) {
        if (err instanceof Error && err.message.startsWith(sub.student.enrollmentNo)) throw err;
        throw new Error(`The PDF for ${label} could not be read and the merge was stopped.`);
      }

      pageMap.push({
        enrollmentNo: sub.student.enrollmentNo,
        name: sub.student.name,
        startPage,
        endPage: out.getPageCount(),
      });

      await setStep(jobId, "MERGING", 20 + Math.round((i / submissions.length) * 55));
    }

    if (options.tableOfContents && tocPages.length > 0) {
      let page = tocPages[0];
      let index = 0;
      let y = 780;
      page.drawText("Contents", { x: 60, y, size: 20, font: helvBold, color: INK });
      y -= 34;
      for (const entry of pageMap) {
        if (y < 60) {
          index += 1;
          if (index >= tocPages.length) break;
          page = tocPages[index];
          y = 790;
        }
        const left = `${entry.enrollmentNo}  ${entry.name}`;
        const right = String(entry.startPage);
        page.drawText(left, { x: 60, y, size: 10, font: helv, color: INK });
        const rw = helv.widthOfTextAtSize(right, 10);
        page.drawText(right, { x: A4[0] - 60 - rw, y, size: 10, font: helv, color: MUTED });
        y -= 20;
      }
    }

    if (options.pageNumbers) {
      const pages = out.getPages();
      pages.forEach((p, i) => {
        const text = `${i + 1} / ${pages.length}`;
        const w = helv.widthOfTextAtSize(text, 9);
        p.drawText(text, { x: (A4[0] - w) / 2, y: 24, size: 9, font: helv, color: MUTED });
      });
    }

    await setStep(jobId, "UPLOADING", 85);

    const pdfBytes = Buffer.from(await out.save());
    const stamp = new Date().toISOString().slice(0, 10);
    const filename = `Final_${job.assignment.slug}_${stamp}_v${job.version}.pdf`;

    const uploadedFile = await store.saveFinal(filename, pdfBytes);

    await prisma.mergeJob.update({
      where: { id: jobId },
      data: {
        status: "SUCCESS",
        step: "DONE",
        progress: 100,
        totalPages: out.getPageCount(),
        outputDriveFileId: uploadedFile.id,
        outputUrl: uploadedFile.webViewLink,
        outputFilename: filename,
        pageMap: { options, entries: pageMap },
        finishedAt: new Date(),
      },
    });

    await prisma.assignment.update({
      where: { id: job.assignmentId },
      data: { status: "MERGED" },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Merge failed";
    console.error("[merge]", err);
    await prisma.mergeJob.update({
      where: { id: jobId },
      data: { status: "FAILED", step: "FAILED", error: message, finishedAt: new Date() },
    });
  }
}
